replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: ghcr.io/wcorn/toy
  tag: 000f0029cca4223817630a230a52023dd6fc87c1
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80

selector:
  app: peter-service-pod
healthCheck:
  app: peter-health-check
canary:
  maxSurge: 1
  maxUnavailable: 0
  steps:
    - setWeight: 50
    - pause:
        duration: 30s
    - analysis:
        templates:
          - templateName: peter-health-check
    - setWeight: 100