replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: ghcr.io/wcorn/toy
  tag: b8597f15e7d49416727e74d695ac801495cc9d3a
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 9000

selector:
  app: peter-service-pod

canary:
  maxSurge: 1
  maxUnavailable: 0
  steps:
    - setWeight: 50
    - pause: {duration: 30s}
    - analysis:
        templates:
          - templateName: peter-health-check
        startingStep: 1 
    - setWeight: 100
