replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: ghcr.io/wcorn/toy
  tag: c19e2a267ba69c7394767e141b00225ac36b9c83
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80

selector:
  app: peter-service-pod
healthCheck:
  app: peter-health-check
canary:
  maxSurge: 1
  maxUnavailable: 0
  steps:
    - setWeight: 50
    - pause:
        duration: 30s
    - analysis:
        templates:
          - templateName: peter-health-check
    - setWeight: 100