apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: peter-health-check
spec:
  metrics:
    - name: peter-availability
      interval: 20s
      successCondition: "result == 200"  #
      failureLimit: 3
      provider:
        web:
          url: "http://peter-service.toy.svc.cluster.local:{{ .Values.service.targetPort }}/"
          timeout: 2s
