apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: peter-service-rollout
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
      - name: peter-rollout
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
  strategy:
    canary:
      maxSurge: {{ .Values.canary.maxSurge }}
      maxUnavailable: {{ .Values.canary.maxUnavailable }}
      steps:
      {{- toYaml .Values.canary.steps | nindent 6 }}