apiVersion: v1
kind: Service
metadata:
  name: peter-service
spec:
  selector:
    app: {{ .Values.selector.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}