apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/wcorn/toy-gitops.git
    targetRevision: main
    path: charts/nginx-ingress
  
  destination:
    server: https://kubernetes.default.svc
    namespace: toy
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - 'CreateNamespace=true'